language: r
os: linux
dist: bionic
cache: packages
warnings_are_errors: false

addons:
  apt:
    update: true
    packages:
    - libudunits2-dev
    - libgdal-dev
    - libproj-dev
    - libgeos-dev

env:
  global:
  - NOT_CRAN=true
  
